# Generated by Django 3.2.6 on 2021-08-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas1', '0003_auto_20210814_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
