# Generated by Django 3.2.6 on 2021-08-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas1', '0004_auto_20210814_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSerializer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
