# Generated by Django 3.2.6 on 2021-08-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas1', '0005_userserializer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSerializer',
        ),
    ]
