# Generated by Django 3.2.6 on 2021-08-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas1', '0006_delete_userserializer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_course',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='user_course',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User_course',
        ),
    ]
