# Generated by Django 3.2.6 on 2021-08-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas1', '0009_auto_20210815_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='submission',
            field=models.ManyToManyField(blank=True, to='kanvas1.Submission'),
        ),
    ]
