# Generated by Django 3.2.6 on 2021-08-15 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanvas1', '0010_alter_activity_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='submission',
        ),
        migrations.AlterField(
            model_name='submission',
            name='activity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanvas1.activity'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='repo',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user_id',
        ),
        migrations.AddField(
            model_name='submission',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
