# Generated by Django 3.2.6 on 2021-08-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas1', '0011_auto_20210815_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='submissions',
            field=models.ManyToManyField(related_name='Submission', to='kanvas1.Submission'),
        ),
    ]
