# Generated by Django 3.2.6 on 2021-08-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas1', '0012_activity_submissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='user_id',
            new_name='user',
        ),
    ]
