# Generated by Django 3.2.6 on 2021-08-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanvas1', '0014_alter_submission_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
